name: Simple Python action

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - zerpiko/*

jobs:
  build:
    runs-on: macOS 
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7]

    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        python -m pytest tests/
